services:
    auto:
        container_name: auto
        image: auto
        build:
            dockerfile: Dockerfile
        volumes:
            - cache:/home/auto/.cache
            # - ./data:/home/auto/sd/data
            # - ./outputs:/home/auto/sd/outputs
            - /mnt/ml/sd-docker/data:/home/auto/sd/data
            - /mnt/ml/sd-docker/outputs:/home/auto/sd/outputs
        ports:
            - 7860:7860
        command:
            - python
            - launch.py
            - --listen
            - --xformers
            - --data-dir=/home/auto/sd/data
            - --embeddings-dir=/home/auto/sd/data/embeddings
            - --allow-code
            - --enable-insecure-extension-acces
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
                          device_ids: ['0']

volumes:
    cache:
