##
#  Cuda basis for stable-diffusion-webui.
#  There doesn't seem to be any benefit to having cuda installed.
#  For some experiments, this image may be useful
##
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

# Hide some banner stuff
RUN rm /opt/nvidia/entrypoint.d/15-container-copyright.txt
RUN rm /opt/nvidia/entrypoint.d/30-container-license.txt
RUN rm /opt/nvidia/entrypoint.d/10-banner.sh

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl git build-essential libgl1

# Install Python
RUN apt-get install -y python3 python3-pip python3-venv

# Switch to non root user
RUN adduser auto
USER auto

# Setup Virtualenv
ENV VIRTUAL_ENV=/home/auto/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Python Deps
RUN pip3 install -U pip setuptools wheel
RUN pip3 install torch --no-cache-dir

# Move to top later
USER root
RUN apt-get install -y libgoogle-perftools-dev
RUN apt-get install -y libgles2-mesa-dev
# ENV LD_PRELOAD=libtcmalloc.so
USER auto


ADD https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/git/refs/heads/master version.json
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git /home/auto/sd

ENV install_dir=/home/auto/sd
RUN /bin/bash -c "/home/auto/sd/webui.sh --skip-torch-cuda-test --exit"
# RUN /home/auto/sd/webui.sh

WORKDIR /home/auto/sd

RUN pip3 install -r requirements_versions.txt
